const PRODUCTS = [
  {name:'Pregnacare Plus Omega-3 Dual Pack 28 Day Supply',category:'Omega-3',primary:'pregnancy',goals:['energy','focus','heart','immune','kids','pregnancy'],who:['adult','woman'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Optibac For Pregnancy X30',category:'Probiotics',primary:'gut',goals:['energy','gut','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Vitabiotics Wellwoman 50+ Multivitamin 30 Tablets',category:'Women\'s Multivitamin',primary:'womens',goals:['energy','hair','immune','skin','womens'],who:['adult','woman'],warnings:{}},
  {name:'Vitabiotics Wellwoman 70+ Multivitamin 30 Tablets',category:'Women\'s Multivitamin',primary:'womens',goals:['energy','hair','immune','skin','womens'],who:['adult','woman'],warnings:{}},
  {name:'Seven Seas Cod Liver Oil Plus Multivitamin 90 Capsules',category:'Omega-3',primary:'heart',goals:['energy','eye','heart','immune','liver'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Wellwoman Original Multivitamin 30 Capsules',category:'Women\'s Multivitamin',primary:'womens',goals:['energy','hair','immune','skin','womens'],who:['adult','woman'],warnings:{}},
  {name:'Equazen Eye Q Capsules X60',category:'Brain Omega-3',primary:'focus',goals:['eye','focus','heart','kids'],who:['baby'],warnings:{}},
  {name:'Quest BioFolic X60 Tablets',category:'Pregnancy',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Equazen Eye Q Capsules X180',category:'Brain Omega-3',primary:'focus',goals:['eye','focus','heart','kids'],who:['baby'],warnings:{}},
  {name:'Healthaid Folic Acid 400Ug X90',category:'Folic Acid',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Equazen Eye Q Baby Capsules X30',category:'Brain Omega-3',primary:'focus',goals:['eye','focus','heart','kids'],who:['baby'],warnings:{}},
  {name:'Quest Folic Acid 400Mcg X 90 Tablets',category:'Folic Acid',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Natures Aid Folic Acid 400Ug X90 Tablets',category:'Folic Acid',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Vitabiotics Pregnacare Original 30 Tablets',category:'Pregnancy',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Chewy Vites Kids Multi Vitamin + Probiotic X60',category:'Probiotics',primary:'gut',goals:['energy','gut','immune','kids'],who:['baby'],warnings:{}},
  {name:'Vitabiotics Visionace Plus Omega-3 28 Day Supply',category:'Omega-3',primary:'heart',goals:['energy','eye','heart','immune'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Equazen Eye Q Children\'s Liquid Syrup Citrus 200Ml',category:'Brain Omega-3',primary:'focus',goals:['eye','focus','heart','kids'],who:['baby'],warnings:{}},
  {name:'Vitabiotics Pregnacare Before Conception 30 Tablets',category:'Pregnancy',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Equazen Eye Q Children\'s Liquid Syrup Vanilla 200Ml',category:'Brain Omega-3',primary:'focus',goals:['eye','focus','heart','kids'],who:['baby'],warnings:{}},
  {name:'Vitabiotics Pregnacare Breast-feeding Dual Pack 28 Day Supply',category:'Pregnancy',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Centrum Kids Chewable  X 30',category:'Multivitamin',primary:'energy',goals:['energy','immune','kids'],who:['baby'],warnings:{}},
  {name:'Centrum Fruity Chewables  X30',category:'Multivitamin',primary:'energy',goals:['energy','immune','kids'],who:['baby'],warnings:{}},
  {name:'Healthaid Menovital 60 Tablets',category:'Menopause Support',primary:'menopause',goals:['energy','immune','menopause'],who:['adult','woman'],warnings:{}},
  {name:'Erba Vita Calma B Baby Syrup 150Ml',category:'Children\'s Health',primary:'sleep',goals:['kids','sleep','stress'],who:['baby'],warnings:{}},
  {name:'Erba Vita Mucovit Junior Syrup 200Ml',category:'Children\'s Health',primary:'cold',goals:['cold','immune','kids'],who:['baby'],warnings:{}},
  {name:'Vichy Anti-Sand Spray Child 50+ 200Ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'Chewy Vites Kids Multi-VIt + Iron X60',category:'Iron',primary:'energy',goals:['energy','gut','kids'],who:['baby'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Vitabiotics Visionace Max 28 Day Supply',category:'Multivitamin',primary:'energy',goals:['energy','eye','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Wellman Prostace 60 Tablets',category:'Men\'s Multivitamin',primary:'mens',goals:['energy','immune','mens'],who:['adult','man'],warnings:{}},
  {name:'Advancis Omega-3 Super EPA X30 Capsules',category:'Omega-3',primary:'heart',goals:['eye','focus','heart'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Erba Vita Multivitamin Kids Gummies X30',category:'Multivitamin',primary:'kids',goals:['energy','immune','kids'],who:['baby'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Wellman Original Multivitamin 30 Tablets',category:'Men\'s Multivitamin',primary:'mens',goals:['energy','immune','mens'],who:['adult','man'],warnings:{}},
  {name:'Chewy Vites Adults Hair Skin & Nails X60',category:'Supplement',primary:'kids',goals:['hair','kids','skin'],who:['baby'],warnings:{}},
  {name:'Health Aid Echinacea Liquid Children 50Ml',category:'Echinacea',primary:'immune',goals:['cold','immune','kids'],who:['baby'],warnings:{}},
  {name:'Vitabiotics Wellman Conception 30 Tablets',category:'Men\'s Multivitamin',primary:'mens',goals:['energy','immune','mens'],who:['adult','man'],warnings:{}},
  {name:'Bioderma Photoderm Pediatrics Milk SPF50+',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'La Roche-Posay Effaclar Duo (+) SPF30 40ml',category:'Sun Protection',primary:'sunburn',goals:['skin','sunburn','weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Chewy Vites Kids Multi-Vitamin Advance X60',category:'Vitamin A',primary:'kids',goals:['energy','immune','kids'],who:['baby'],warnings:{}},
  {name:'Chewy Vites Super Immune Adult Gummies X60',category:'Probiotics',primary:'kids',goals:['gut','immune','kids'],who:['baby'],warnings:{}},
  {name:'Seven Seas JointCare + Collagen 60 Capsules',category:'Collagen',primary:'skin',goals:['heart','joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Hair Skin Nails Vitamin X30 Tablets',category:'Multivitamin',primary:'energy',goals:['energy','hair','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Eucerin Sun Protection Kids Spray Spf50+200Ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'Healthaid Baby Vitamin MultiVitamin Drops 25Ml',category:'Vitamin D',primary:'kids',goals:['energy','immune','kids'],who:['baby'],warnings:{}},
  {name:'Natures Aid Cod Liver Oil 1000Mg X 90 Softgels',category:'Omega-3',primary:'heart',goals:['eye','heart','liver'],who:['adult','woman','man'],warnings:{}},
  {name:'ActiKid Multi-Vitamin Drops Orange Flavour 25ML',category:'Vitamin D',primary:'kids',goals:['energy','immune','kids'],who:['baby'],warnings:{}},
  {name:'Vitabiotics Wellman 50+ Multivitamin 30 Tablets',category:'Men\'s Multivitamin',primary:'mens',goals:['energy','immune','mens'],who:['adult','man'],warnings:{}},
  {name:'Vitabiotics Wellman 70+ Multivitamin 30 Tablets',category:'Men\'s Multivitamin',primary:'mens',goals:['energy','immune','mens'],who:['adult','man'],warnings:{}},
  {name:'Puressentiel Respiratory Kids Cough Syrup 140Ml',category:'Children\'s Health',primary:'cold',goals:['cold','immune','kids'],who:['baby'],warnings:{}},
  {name:'Chewy Vites Super Foods Apple Cider Vinegar X60',category:'Supplement',primary:'kids',goals:['energy','kids','weight'],who:['baby'],warnings:{}},
  {name:'Bioderma Nude Touch Mineral Claire Light SPF50+',category:'Sun Protection',primary:'sunburn',goals:['skin','sunburn','weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Multivitamin Effervescent X20 Tablets',category:'Vitamin E',primary:'energy',goals:['energy','immune','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo Slim Boost Collagen Beauty & Burn X15 Sticks',category:'Collagen',primary:'skin',goals:['joint','skin','weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid Radiance Hydrolysed Collagen X60 Tablets',category:'Collagen',primary:'skin',goals:['hair','joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Wellkid Multivitamin 30 ChewableTablets',category:'Multivitamin',primary:'kids',goals:['energy','immune','kids'],who:['baby'],warnings:{}},
  {name:'Forte Pharma Immuvit Junior 4G X30 Chewable Tablets',category:'Children\'s Health',primary:'energy',goals:['energy','immune','kids'],who:['baby'],warnings:{}},
  {name:'Isdin Fotoprotector Pediatrics Gel Cream SPF50+ 250Ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'Natures Aid Cod Liver Oil 550Mg Omega-3 X120 Softgels',category:'Omega-3',primary:'heart',goals:['eye','heart','liver'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Natures Aid Mini Drops Multivitamin Orange Flavour 50ml',category:'Multivitamin',primary:'kids',goals:['energy','immune','kids'],who:['baby'],warnings:{}},
  {name:'La Roche-Posay Anthelios Invisible Spray 50+ Kids 200Ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'Isdin Fotoprotector Pediatrics Fusion Fluid SPF50+ 50Ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'Seven Seas Cod Liver Oil Plus Vitamin D One a Day Tablets',category:'Vitamin D',primary:'heart',goals:['eye','heart','liver'],who:['adult','woman','man'],warnings:{}},
  {name:'Bioderma Nude Touch Mineral Tres Claire Very Light SPF50+',category:'Sun Protection',primary:'sunburn',goals:['skin','sunburn','weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Osteocare Plus Omega-3 Dual-Pack 28 Day Supply',category:'Calcium',primary:'heart',goals:['eye','heart','joint'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Vitabiotics Perfectil Original Hair, Skin and Nails 30 Tablets',category:'Supplement',primary:'immune',goals:['hair','immune','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Equazen Chews Strawberry Flavour 60 Chewable Capsules 3+ Years',category:'Brain Omega-3',primary:'focus',goals:['focus','heart','kids'],who:['baby'],warnings:{}},
  {name:'Equazen Chews Strawberry Flavour 180 Chewable Capsules 3+ Years',category:'Brain Omega-3',primary:'focus',goals:['focus','heart','kids'],who:['baby'],warnings:{}},
  {name:'ActiKid Magic Beans Multi-Vitamin Vegan Mixed Fruit Flavour X60',category:'Children\'s Health',primary:'kids',goals:['energy','immune','kids'],who:['baby'],warnings:{}},
  {name:'La Roche-Posay Anthelios Dermo-Pediatrics Baby Lotion SPF50+ 50ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'La Roche-Posay Anthelios Dermo-Peadiatrics Hydrating Lotion 50+ 75Ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'Isdin Fotoprotector Pediatrics Transparent Spray Wet Skin SPF50+ 250Ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'La Roche-Posay Anthelios Dermo-Pediatrics Wet Skin Lotion Eco-Tube SPF50+ 200ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'La Roche-Posay Anthelios UVMune 400 Dermo-Pediatrics Hydrating Lotion SPF50+ 250Ml',category:'Sun Protection',primary:'sunburn',goals:['kids','skin','sunburn'],who:['baby'],warnings:{}},
  {name:'Efamol Liquid 150Ml',category:'Brain Omega-3',primary:'focus',goals:['focus','heart'],who:['adult','woman','man'],warnings:{}},
  {name:'Optibac For Women X14',category:'Probiotics',primary:'gut',goals:['gut','womens'],who:['adult','woman'],warnings:{}},
  {name:'Optibac For Women X30',category:'Probiotics',primary:'gut',goals:['gut','womens'],who:['adult','woman'],warnings:{}},
  {name:'Optibac For Women X90',category:'Probiotics',primary:'gut',goals:['gut','womens'],who:['adult','woman'],warnings:{}},
  {name:'Centrum Men X 30 Tablets',category:'Multivitamin',primary:'mens',goals:['energy','immune'],who:['adult','man'],warnings:{}},
  {name:'Centrum Women X 30 Tablets',category:'Multivitamin',primary:'womens',goals:['energy','immune'],who:['adult','woman'],warnings:{}},
  {name:'Centrum Men 50+ X 30 Tablets',category:'Multivitamin',primary:'mens',goals:['energy','immune'],who:['adult','man'],warnings:{}},
  {name:'Jointace Max Triple Pack X84',category:'Supplement',primary:'joint',goals:['heart','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Centrum Advance X 100 Tablets',category:'Multivitamin',primary:'energy',goals:['energy','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Jointace Omega-3 X30 Capsules',category:'Omega-3',primary:'heart',goals:['heart','joint'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Jointace Collagen X30 Tablets',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Calmbiotix X30 Capsules',category:'Supplement',primary:'stress',goals:['energy','stress'],who:['adult','woman','man'],warnings:{}},
  {name:'Optibac Women\'s Wellbeing X30',category:'Probiotics',primary:'gut',goals:['gut','womens'],who:['adult','woman'],warnings:{}},
  {name:'Advancis Super Food X20 Vials',category:'Weight Management',primary:'focus',goals:['focus','weight'],who:['adult','woman','man'],warnings:{}},
  {name:'ActiKid Vitamin D3 Drops 5.3ML',category:'Vitamin D',primary:'kids',goals:['immune','kids'],who:['baby'],warnings:{}},
  {name:'Berocca 30 Film-Coated Tablets',category:'Multivitamin',primary:'energy',goals:['energy','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Centrum Women 50+ X 30 Tablets',category:'Multivitamin',primary:'mens',goals:['energy','immune'],who:['adult','woman'],warnings:{}},
  {name:'Quest Cranbiotix Capsules X 30',category:'Probiotics',primary:'uti',goals:['gut','uti'],who:['adult','woman','man'],warnings:{}},
  {name:'Manuka Health MGO Manuka Honey',category:'Manuka Honey',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Chewy Vites Kids Magnesium X60',category:'Magnesium',primary:'kids',goals:['gut','kids'],who:['baby'],warnings:{}},
  {name:'Healthaid Calmagzinc 90 Tablets',category:'Zinc',primary:'stress',goals:['immune','stress'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Ubiquinol Qu 10 100Mg X30',category:'CoQ10',primary:'energy',goals:['energy','heart'],who:['adult','woman','man'],warnings:{}},
  {name:'Femarelle Recharge X56 Capsules',category:'Menopause Support',primary:'menopause',goals:['menopause','mens'],who:['adult','man'],warnings:{}},
  {name:'Nupo Care+ | Premium Fibre 190g',category:'Meal Replacement',primary:'weight',goals:['gut','weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Erba Vita Vitamin C Gummies X30',category:'Vitamin C',primary:'kids',goals:['immune','kids'],who:['baby'],warnings:{}},
  {name:'Puressentiel Respiratory Inhaler',category:'Health Supplement',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Centrum Advance 50+  X 60 Tablets',category:'Multivitamin',primary:'energy',goals:['energy','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Ashwagandha X60 Tablets',category:'Ashwagandha',primary:'stress',goals:['sleep','stress'],who:['adult','woman','man'],warnings:{}},
  {name:'Efamol Active Memory x30 Capsules',category:'Brain Omega-3',primary:'focus',goals:['focus','heart'],who:['adult','woman','man'],warnings:{}},
  {name:'Femarelle Rejuvenate X56 Capsules',category:'Menopause Support',primary:'menopause',goals:['menopause','mens'],who:['adult','man'],warnings:{}},
  {name:'Quest Stress B Complex x30 Tablets',category:'Vitamin B',primary:'stress',goals:['energy','stress'],who:['adult','woman','man'],warnings:{}},
  {name:'Femarelle Unstoppable X56 Capsules',category:'Menopause Support',primary:'menopause',goals:['menopause','mens'],who:['adult','man'],warnings:{}},
  {name:'Natures Aid Immune Plus Drops 50ml',category:'Children\'s Health',primary:'immune',goals:['immune','kids'],who:['baby'],warnings:{}},
  {name:'Quest Coenzyme Q10 30Mg X30 Tablets',category:'CoQ10',primary:'energy',goals:['energy','heart'],who:['adult','woman','man'],warnings:{}},
  {name:'Optibac Kids Strawberry Gummies X30',category:'Probiotics',primary:'gut',goals:['gut','kids'],who:['baby'],warnings:{}},
  {name:'Chewy Vites Kids Immune Support X60',category:'Children\'s Health',primary:'immune',goals:['immune','kids'],who:['baby'],warnings:{}},
  {name:'Healthaid Biotin 5000Ug X60 Tablets',category:'Biotin',primary:'skin',goals:['hair','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Echinacea 500Mg 60 Tablets',category:'Echinacea',primary:'immune',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Eucerin Sun Aftersun Creme Gel 200Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Optibac Adult Strawberry Gummies X30',category:'Probiotics',primary:'gut',goals:['gut','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Ashwagandha 500Mg X60 Capsules',category:'Ashwagandha',primary:'stress',goals:['sleep','stress'],who:['adult','woman','man'],warnings:{}},
  {name:'Erba Vita Mucovit Adults Syrup 200Ml',category:'Health Supplement',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Liposomal Collagen X30 Sachets',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Milk Thistle X60 Box/Bottle',category:'Milk Thistle',primary:'liver',goals:['energy','liver'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Omega 3 750Mg X 60 Capsules',category:'Omega-3',primary:'heart',goals:['eye','heart'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Health Aid Omega 3 750Mg X30 Capsules',category:'Omega-3',primary:'heart',goals:['eye','heart'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'ActiKid Magic Beans Orange Flavour X90',category:'Children\'s Health',primary:'immune',goals:['immune','kids'],who:['baby'],warnings:{}},
  {name:'Healthaid Echinacea Liquid Adults 50Ml',category:'Echinacea',primary:'immune',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Hyaluronic 55Mg X 30 Tablets',category:'Hyaluronic Acid',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Mini Vitamin D3 Drops 50ml',category:'Vitamin D',primary:'kids',goals:['immune','kids'],who:['baby'],warnings:{}},
  {name:'Puressentiel Sinus Express X15 Tablets',category:'Health Supplement',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Iron Mini Drops 400Iu 50ml',category:'Iron',primary:'energy',goals:['energy','kids'],who:['baby'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Isdin Post Solar After Sun Spray 200Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Agnus Castus 550Mg 60 Tablets',category:'Agnus Castus',primary:'menopause',goals:['menopause','womens'],who:['adult','woman'],warnings:{}},
  {name:'Healthaid Day-Vitamin Active 30 Tablets',category:'Vitamin A',primary:'energy',goals:['energy','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid L-Carnitine 550Mg 30 Tablets',category:'L-Carnitine',primary:'energy',goals:['energy','weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Immune System Biotix X30 Capsules',category:'Probiotics',primary:'immune',goals:['gut','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Vichy Ideal Soleil After Sun Milk 300Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Optibac Babies And Children X10 Sachets',category:'Probiotics',primary:'gut',goals:['gut','kids'],who:['baby'],warnings:{}},
  {name:'Optibac Babies And Children X30 Sachets',category:'Probiotics',primary:'gut',goals:['gut','kids'],who:['baby'],warnings:{}},
  {name:'Optibac Babies And Children X90 Sachets',category:'Probiotics',primary:'gut',goals:['gut','kids'],who:['baby'],warnings:{}},
  {name:'Healthaid Milk Thistle 500Mg X30 Tablets',category:'Milk Thistle',primary:'liver',goals:['energy','liver'],who:['adult','woman','man'],warnings:{}},
  {name:'Efamol Efalex Brain Formula X60 Capsules',category:'Brain Omega-3',primary:'focus',goals:['focus','heart'],who:['adult','woman','man'],warnings:{}},
  {name:'Forte Pharma Expert Collagen X14 Sachets',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Bee Propolis 1000Mg *60 Tablets',category:'Bee Propolis',primary:'immune',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Osteocare Original 90 Tablets',category:'Calcium',primary:'immune',goals:['immune','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Osteocare Original 30 Tablets',category:'Calcium',primary:'immune',goals:['immune','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Omega 3 Fish Oil 90 Capsules 1000Mg',category:'Omega-3',primary:'heart',goals:['eye','heart'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'La Roche-Posay Posthelios Hydra Gel 200Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Chewy Vites Kids Calcium & Vitamin D3 X60',category:'Vitamin D',primary:'kids',goals:['joint','kids'],who:['baby'],warnings:{}},
  {name:'Igennus Pure Biotin 10,000Ug X180 Tablets',category:'Biotin',primary:'skin',goals:['hair','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Chewy Vites Adults Iron High Strength X60',category:'Iron',primary:'energy',goals:['energy','kids'],who:['baby'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Healthaid Biotin 800Mcg Vitamin 30 Tablets',category:'Biotin',primary:'skin',goals:['hair','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Coenergy Coq10 30Mg X30 Capsules',category:'CoQ10',primary:'energy',goals:['energy','heart'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Osteocare Chewables 30 Tablets',category:'Calcium',primary:'immune',goals:['immune','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Puressentiel Respiratory Cough Syrup 125Ml',category:'Health Supplement',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Advancis Vitamin C + Echinacea X30 Tablets',category:'Vitamin C',primary:'immune',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Seven Seas JointCare + Calcium 60 Capsules',category:'Calcium',primary:'joint',goals:['heart','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Starflower Oil 1000Mg X30 Capsules',category:'Evening Primrose Oil',primary:'womens',goals:['skin','womens'],who:['adult','woman'],warnings:{}},
  {name:'Bioderma Photoderm After-Sun Gel-Cream 200ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Starflower Oil 1000mg X60 Capsules',category:'Evening Primrose Oil',primary:'womens',goals:['skin','womens'],who:['adult','woman'],warnings:{}},
  {name:'Health Aid Coq10 Co Enzyme 120Mg X30 Capsules',category:'CoQ10',primary:'energy',goals:['energy','heart'],who:['adult','woman','man'],warnings:{}},
  {name:'La Roche-Posay Posthelios After Sun Gel 200Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Erba Vita Propoli EVSP Effer Prop X20 Tablets',category:'Health Supplement',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Collagen Beauty Formula 90 Tablets',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Biogena Ashwagandha Relax Formula X60 Capsules',category:'Ashwagandha',primary:'stress',goals:['sleep','stress'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Fish Oil 1000Mg 90+30 Free Softgels',category:'Omega-3',primary:'heart',goals:['eye','heart'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Natures Aid Super Strength Fish Oil 60 Softgels',category:'Omega-3',primary:'heart',goals:['eye','heart'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Forte Pharma Expert Beauty Marine Collagen 230G',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Seven Seas JointCare Max Glucosamine 60 Capsules',category:'Glucosamine',primary:'joint',goals:['heart','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Forte Pharma Forte Flex Max Joint Collagen+ 260G',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Menopace + Calcium Vitamin 60 Tablets',category:'Calcium',primary:'menopause',goals:['joint','menopause'],who:['adult','woman'],warnings:{}},
  {name:'Bioderma ABCderm Peri Oral Mouth Irritations 40Ml',category:'Children\'s Health',primary:'skin',goals:['kids','skin'],who:['baby'],warnings:{}},
  {name:'Natures Aid Fish Oil 1000Mg Omega-3 X240 Softgels',category:'Omega-3',primary:'heart',goals:['eye','heart'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Seven Seas JointCare Supplex & Turmeric 60 Tablets',category:'Turmeric',primary:'joint',goals:['heart','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Bioderma ABCderm Cold-Cream Nourishing Cream 200Ml',category:'Children\'s Health',primary:'skin',goals:['kids','skin'],who:['baby'],warnings:{}},
  {name:'Healthaid Evening Primrose oil (EPO) 500Mg Capsules',category:'Evening Primrose Oil',primary:'womens',goals:['skin','womens'],who:['adult','woman'],warnings:{}},
  {name:'Manuka Health Manuka Honey Lemon MGO 400+ X15 Drops',category:'Manuka Honey',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo One Meal +Prime Soft Baked Apple & Cinnamon 70g',category:'Cinnamon',primary:'weight',goals:['blood_sugar','weight'],who:['adult','woman','man'],warnings:{diabetes:'⚠️ If you are diabetic or on blood sugar medication, consult your doctor before use as this may affect glucose levels.'}},
  {name:'Quest Vitamin C + Zinc 1000MG Effervescent X20 Tablets',category:'Vitamin C',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Osteocare Liquid Syrup Orange Flavour 200ml',category:'Calcium',primary:'immune',goals:['immune','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Evening Primrose oil (EPO) 1000Mg + Vitamin E',category:'Vitamin E',primary:'womens',goals:['skin','womens'],who:['adult','woman'],warnings:{}},
  {name:'Healthaid Evening Primrose oil (EPO) 1300Mg X30 Capsules',category:'Evening Primrose Oil',primary:'womens',goals:['skin','womens'],who:['adult','woman'],warnings:{}},
  {name:'Vitabiotics Osteocare Fizz Orange 20 Effervescent Tablets',category:'Calcium',primary:'immune',goals:['immune','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Seven Seas Omega-3 Fish Oil + CLO Max Strength Liquid 100Ml',category:'Omega-3',primary:'heart',goals:['eye','heart'],who:['adult','woman','man'],warnings:{bloodthinners:'⚠️ May interact with blood-thinning medication. Please consult your doctor or pharmacist before use.'}},
  {name:'Manuka Health Manuka Honey with Propolis MGO 400+ X15 Drops',category:'Bee Propolis',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Manuka Health Manuka Honey Ginger & Lemon MGO 400+ X15 Drops',category:'Manuka Honey',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Forte Pharma Expert Beauty Marine Collagen Intense+ 15G - 300G',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'La Roche-Posay Anthelios Post-UV Exposure After-Sun Lotion 200Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Forte Pharma Forte Flex D-Contract\' Muscles Marine Collagen 334G',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Manuka Health Manuka Honey with Propolis Oral Spray MGO 400+ 20Ml',category:'Bee Propolis',primary:'cold',goals:['cold','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Bioderma ABCderm Hydratant Moisturising Nutri-Protective Milk 200Ml',category:'Children\'s Health',primary:'skin',goals:['kids','skin'],who:['baby'],warnings:{}},
  {name:'Healthaid Royal 3 Evening Primrose Royal Jelly &amp; Ginseng X30 Capsules',category:'Evening Primrose Oil',primary:'womens',goals:['skin','womens'],who:['adult','woman'],warnings:{}},
  {name:'XtraSlim 700 Men',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','man'],warnings:{}},
  {name:'Nupo Shaker 400Ml',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'XtraSlim 700 Woman',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman'],warnings:{}},
  {name:'Healthaid Vitamin B6',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'XtraSlim 700 Woman 45+',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman'],warnings:{}},
  {name:'Erba Vita Coli B 150Ml',category:'Children\'s Health',primary:'kids',goals:['kids'],who:['baby'],warnings:{}},
  {name:'BetterYou Iron 5mg 25Ml',category:'Iron',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Erba Vita Immuno B 150Ml',category:'Children\'s Health',primary:'kids',goals:['kids'],who:['baby'],warnings:{}},
  {name:'Medicare Nasal Aspirator',category:'Children\'s Health',primary:'kids',goals:['kids'],who:['baby'],warnings:{}},
  {name:'BetterYou Vitamin C 50Ml',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'BetterYou Iron 10mg 25Ml',category:'Iron',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'BetterYou B12 Boost 25Ml',category:'Vitamin B12',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Cinnamon Oil 10Ml',category:'Cinnamon',primary:'blood_sugar',goals:['blood_sugar'],who:['adult','woman','man'],warnings:{diabetes:'⚠️ If you are diabetic or on blood sugar medication, consult your doctor before use as this may affect glucose levels.'}},
  {name:'Healthaid Vitamin E Oil 50Ml',category:'Vitamin E',primary:'skin',goals:['skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin E Capsules',category:'Vitamin E',primary:'skin',goals:['skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Walmark Urenal x30 Soft Gels',category:'Urinary Support',primary:'uti',goals:['uti'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Forte Cran Sachets X15',category:'Cranberry',primary:'uti',goals:['uti'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Aloe Vera Gel 250Ml',category:'Aloe Vera',primary:'gut',goals:['gut'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Liverbiotix X30 Tablets',category:'Liver Support',primary:'liver',goals:['liver'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo One Meal Bar Caramel 60g',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Valerian Tablets X60',category:'Valerian',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin B5 690Mg X30',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin C Powder 60G',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin E Cream 75Ml',category:'Vitamin E',primary:'skin',goals:['skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Liposomal Curcumin 600mg',category:'Turmeric',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin D3 30 Tablets',category:'Vitamin D',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo One Meal Bar Chocolate 60g',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Chewy Vites Vitamin D3 Kids X60',category:'Vitamin D',primary:'kids',goals:['kids'],who:['baby'],warnings:{}},
  {name:'Erba Vita Vitamin D Gummies X30',category:'Vitamin D',primary:'kids',goals:['kids'],who:['baby'],warnings:{}},
  {name:'Quest Liposomal Vitamin C 500mg',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Garlic Oil 2Mg Tablets',category:'Garlic',primary:'heart',goals:['heart'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Liposomal Iron 15mg 30caps',category:'Iron',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Chewy Vites Adult Vitamin D3 X60',category:'Vitamin D',primary:'kids',goals:['kids'],who:['baby'],warnings:{}},
  {name:'Nupo Diet Shake | Vanilla 10x32g',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Turmeric X30 Capsules',category:'Turmeric',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Laborest Kistinox Act X14 Sachets',category:'Urinary Support',primary:'uti',goals:['uti'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo Diet Meal Egg Omlette 10x34g',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Synergistic Iron X90 Tablets',category:'Iron',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Nupo Diet Shake | Chocolate 12x32g',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Moringa Leaf Capsules X60',category:'Spirulina',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo One Meal Bar Toffee Crunch 60g',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo One Meal +Prime Vanilla  330ml',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'BetterYou Magnesium Oil Joint 100Ml',category:'Magnesium',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'BetterYou Magnesium Oil Sleep 100Ml',category:'Magnesium',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Turmeric 750Mg *60 Tablets',category:'Turmeric',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin B12 1000Μg Tablets',category:'Vitamin B12',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Laborest Unicozen Vitamin Drops 30Ml',category:'Vitamin D',primary:'kids',goals:['kids'],who:['baby'],warnings:{}},
  {name:'Nupo Slim Boost Burn My Fat X30 Caps',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo One Meal Bar Chocolate Mint 60g',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo One Meal Bar Brownie Crunch 60g',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo Diet Shake | Caffe Latte 12x32g',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Nupo One Meal +Prime Chocolate 330ml',category:'Meal Replacement',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Forté Pharma Zinc Liposomal X60 Caps',category:'Zinc',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Aloe Vera 5000Mg 30 Tablets',category:'Aloe Vera',primary:'gut',goals:['gut'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Rhodiola 500Mg X 60 Tablets',category:'Rhodiola',primary:'stress',goals:['stress'],who:['adult','woman','man'],warnings:{}},
  {name:'BetterYou Vitamin D 400IU Infant 15Ml',category:'Vitamin D',primary:'kids',goals:['kids'],who:['baby'],warnings:{}},
  {name:'Healthaid Cinnamon 850Mcg X30 Capsules',category:'Cinnamon',primary:'blood_sugar',goals:['blood_sugar'],who:['adult','woman','man'],warnings:{diabetes:'⚠️ If you are diabetic or on blood sugar medication, consult your doctor before use as this may affect glucose levels.'}},
  {name:'Healthaid Green Tea Tablets 1000Mg X60',category:'Green Tea',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Glucosamine Sulphate Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin B Complex 30 Capsules',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Alpha Lipoic Acid 60 Capsules',category:'Alpha Lipoic Acid',primary:'blood_sugar',goals:['blood_sugar'],who:['adult','woman','man'],warnings:{diabetes:'⚠️ If you are diabetic or on blood sugar medication, consult your doctor before use as this may affect glucose levels.'}},
  {name:'Healthaid Choline Inositol X60 Capsules',category:'Choline',primary:'focus',goals:['focus'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Cranberry 5000Mg X60 Capsules',category:'Cranberry',primary:'uti',goals:['uti'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Saw Palmetto 265mg 30 Tablets',category:'Saw Palmetto',primary:'mens',goals:['mens'],who:['adult','man'],warnings:{}},
  {name:'Healthaid Vitamin C 500Mg X60 Chewables',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid Aloe Vera 5000Mg X60 Tablets',category:'Aloe Vera',primary:'gut',goals:['gut'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid L-Theanine 200Mg X60 Tablets',category:'L-Theanine',primary:'stress',goals:['stress'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Spirulina 500mg 90 Capsules',category:'Spirulina',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Erba Vita Lietoson Melatonin Drops 30Ml',category:'Melatonin',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'BetterYou Magnesium Oil Sensitive 100Ml',category:'Magnesium',primary:'skin',goals:['skin'],who:['adult','woman','man'],warnings:{}},
  {name:'BetterYou Magnesium Oil Menopause 100Ml',category:'Magnesium',primary:'menopause',goals:['menopause'],who:['adult','woman'],warnings:{}},
  {name:'Healthaid Iron Formula Plus X100 Tablets',category:'Iron',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Healthaid Vitamin B99 Complex 60 Tablets',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin C 1000Mg X30 Chewables',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Zincovit-C Vitamin X60 Tablets',category:'Zinc',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid Iron Bisglycinate X90 Tablets',category:'Iron',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Natures Aid Vitamin B Complex 90 Tablets',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Forte Pharma XtraSlim Max 24 x60 Tablets',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Vitamin C 1000Mg Tablets X240',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Iron Bisglycinate X90 Tablets',category:'Iron',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Healthaid Calcium Strong 600Mg X60 Tablets',category:'Calcium',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid Zinc Gluconate 70Mg X90 Tablets',category:'Zinc',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Glucosamine 1500mg 180 Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Vegan Glucosamine 1500Mg X60 Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Zinc Picolinate 15Mg X30 Tablets',category:'Zinc',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Vitamin B12 1,000mcg X90 Tablets',category:'Vitamin B12',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Calcium Complete 800Mg X120 Tablets',category:'Calcium',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Spirulina 500Mg Vitamin X60 Tablets',category:'Spirulina',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Wintervits + Vitamin C X 30 Tablets',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid Siberian Ginseng 250Mg X30 Capsules',category:'Ginseng',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Synergistic Zinc 15Mg Copper X30 Tablets',category:'Zinc',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin C Tablets Prolongued release',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin B Complex Supreme 90 Capsules',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin C 1000Mg Chewable X60 Tablets',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid Iron Bisglycinate Tablets 30 Tablets',category:'Iron',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Natures Aid Vitamin C 500mg Chewable 50 Tablets',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Vitamin C 1000Mg Effervescent Tablets X20',category:'Vitamin C',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Chromium Picolinate 1800Ug x60 Tablets',category:'Chromium',primary:'blood_sugar',goals:['blood_sugar'],who:['adult','woman','man'],warnings:{diabetes:'⚠️ If you are diabetic or on blood sugar medication, consult your doctor before use as this may affect glucose levels.'}},
  {name:'Healthaid Zinc Sulphate 200Mg Vitamin 90 Tablets',category:'Zinc',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Menopace Original Vitamin 60 Tablets',category:'Menopause Support',primary:'menopause',goals:['menopause'],who:['adult','woman'],warnings:{}},
  {name:'Natures Aid Glucosamine MSM & Chond X180 Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Glucosamine & Chondroitin X90 Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Synergistic Calcium + Vitamin D X45 Tablets',category:'Vitamin D',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid Livercare Prolonged Release x60 Tablets',category:'Liver Support',primary:'liver',goals:['liver'],who:['adult','woman','man'],warnings:{}},
  {name:'Biogena Neurosagena® B-Complex active X60 Capsules',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Glucosamine, MSM & Chond 500Mg X60/90 Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Glucosamine MSM & Chondroitin 90 Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Glucosamine Sulphate 1000Mg X90 Capsules',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Calcium and Vitamin D X20 Effervescent Tablets',category:'Vitamin D',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Immutone Shark Liver Oil 1000mg 30 Capsules',category:'Liver Support',primary:'liver',goals:['liver'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Ginger, Turmeric & Bromelain X60 Capsules',category:'Turmeric',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Glucosamine MSM & Chondroitin X135 Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Erba Vita Magnesium Potassium + Vitamin C Lemon Flavour',category:'Magnesium',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Natures Aid Glucosamine Sulphate 2Kcl 1500Mg X90 Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Erba Vita Magnesium Potassium + Vitamin C Orange Flavour',category:'Magnesium',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin B(Thiamin) 100Mg 90 Prolonged Release Tablets',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin B2 (Riboflavin) 100Mg 60 Prolonged Release Tablets',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Healthaid Vitamin B3 (Niacinamide) 250Mg 90 Prolonged Release Tablets',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Vitabiotics Osteocare Plus Glucosamine & Chondroitin Tablets 60 Tablets',category:'Calcium',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Quest Calcium 500mg & Magnesium + Vitamins D, K, C & B6 Effervescent X20 Tablets',category:'Magnesium',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Foladin X30 Capsules',category:'Pregnancy',primary:'kids',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Caregyn EmulGel 100ml',category:'Pregnancy',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Via Lattea X20 Tablets',category:'Pregnancy',primary:'kids',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Multi-Mam Compresses x12',category:'Pregnancy',primary:'kids',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Active Folic Capsules X60',category:'Pregnancy',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Certain Pregnancy Test x1',category:'Pregnancy',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'GlobiFer Plus X 40 Tablets',category:'Pregnancy',primary:'kids',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Multi-Mam Nipple Balm 30Ml',category:'Pregnancy',primary:'kids',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Chicco Maternity Pads 30Pcs',category:'Pregnancy',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Clearblue Pregnancy Test X2',category:'Pregnancy',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Abopholic Meta Folic Acid Tablets X30',category:'Folic Acid',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Vega Folic Acid 400Ug Vitamin 90 Tablets',category:'Folic Acid',primary:'pregnancy',goals:['energy','immune','kids','pregnancy'],who:['adult','woman'],warnings:{}},
  {name:'Zinc & Castor Oil Cream 200Ml',category:'Zinc',primary:'immune',goals:['immune','kids','skin'],who:['baby'],warnings:{}},
  {name:'Active Iron Multivitamin Men x 60',category:'Iron',primary:'energy',goals:['energy','immune','kids'],who:['baby'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Johnson\'s Baby Oil Aloe Vera 300Ml',category:'Aloe Vera',primary:'gut',goals:['gut','kids','skin'],who:['baby'],warnings:{}},
  {name:'Biorga Cystiphane B6 Zinc Tablets X120 Tablets',category:'Zinc',primary:'energy',goals:['energy','hair','immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Bio 3 Diet Solution Svetol and Biotin X24 Sticks',category:'Biotin',primary:'skin',goals:['hair','skin','weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Weightworld Marine Collagen Advanced X120 Tablets',category:'Collagen',primary:'skin',goals:['immune','joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Nivea After Sun Spray 200Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Nivea Aftersun Bronze 200Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Nivea Aftersun Lotion 200Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Biocinalis+ New Iron Kids 125Ml',category:'Iron',primary:'energy',goals:['energy','kids'],who:['baby'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Maxivita Collagen Forte+ Tabs x60',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Mustela Vitamin Barrier Cream 50Ml',category:'Vitamin B',primary:'kids',goals:['kids','skin'],who:['baby'],warnings:{}},
  {name:'Hawaiian Tropic Aftersun Gel 200Ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Mustela Vitamin Barrier Cream 100Ml',category:'Vitamin B',primary:'kids',goals:['kids','skin'],who:['baby'],warnings:{}},
  {name:'Vital Proteins Marine Collagen 221g',category:'Collagen',primary:'skin',goals:['joint','skin'],who:['adult','woman','man'],warnings:{}},
  {name:'Active Iron Advance 30 Daily Capsules',category:'Iron',primary:'energy',goals:['energy','kids'],who:['baby'],warnings:{default:'⚠️ Do not take iron supplements without confirmed low iron levels. Check with your doctor if unsure.'}},
  {name:'Pantogar for Hair & Nails X90 Capsules',category:'Hair Supplement',primary:'hair',goals:['energy','hair'],who:['adult','woman','man'],warnings:{}},
  {name:'Avène After-Sun Restorative Lotion 200ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Maxivita Calcium Magnesium Zinc Forte+ x60',category:'Magnesium',primary:'immune',goals:['immune','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Uriage Bariésun After-Sun Repair Balm 150ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Vega Calcium Magnesium Plus Zinc 60 Capsules',category:'Magnesium',primary:'immune',goals:['immune','joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Pure Encapsulations Ashwagandha X30 Capsules',category:'Ashwagandha',primary:'stress',goals:['sleep','stress'],who:['adult','woman','man'],warnings:{}},
  {name:'Pure Encapsulations Coenzyme Q10 X30 Capsules',category:'CoQ10',primary:'energy',goals:['energy','heart'],who:['adult','woman','man'],warnings:{}},
  {name:'Uriage Bariésun Refreshing Mist After-Sun 150ml',category:'After Sun',primary:'sunburn',goals:['skin','sunburn'],who:['adult','woman','man'],warnings:{}},
  {name:'Bio 3 Fiber Solution Psyllium Fiber Fruits Peach Flavor X24 Sticks',category:'Weight Management',primary:'gut',goals:['gut','weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Proven Women’s Lactobacillus and Bifidus with Cranberry X30 Capsules',category:'Cranberry',primary:'uti',goals:['gut','uti'],who:['adult','woman'],warnings:{}},
  {name:'Pro-Ven Kids Vitamins C,D & Elderberry Fruit Chewables x60 | Mixed Berry Flavour',category:'Elderberry',primary:'immune',goals:['immune','kids'],who:['baby'],warnings:{}},
  {name:'Bruciakal X45 Tablets',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Moringa 1000 Tablets X45',category:'Spirulina',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Purasana Ashwagandha Caps X60',category:'Ashwagandha',primary:'stress',goals:['stress'],who:['adult','woman','man'],warnings:{}},
  {name:'Body Slim X30 Tea Bags - Lemon',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Melatonin Act Forte Spray 15Ml',category:'Melatonin',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'Vega Garlic Extract High Strength',category:'Garlic',primary:'heart',goals:['heart'],who:['adult','woman','man'],warnings:{}},
  {name:'Bio 3 Weight Control Tea X25 Bags',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Body Slim X30 Tea Bags - Original',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Cistit Act Forte Urto X14 Sachets',category:'Urinary Support',primary:'uti',goals:['uti'],who:['adult','woman','man'],warnings:{}},
  {name:'Proven For Menopause X60 Capsules',category:'Menopause Support',primary:'menopause',goals:['menopause'],who:['adult','woman'],warnings:{}},
  {name:'Bio 3 Dormimax Melatonin X25 Bags',category:'Melatonin',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'Vega Menopause Vitamin Tablets X60',category:'Menopause Support',primary:'menopause',goals:['menopause'],who:['adult','woman'],warnings:{}},
  {name:'ESI Melatonin Pura 1mg x60 Tablets',category:'Melatonin',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'Weightworld Berberine X120 Capsules',category:'Berberine',primary:'blood_sugar',goals:['blood_sugar'],who:['adult','woman','man'],warnings:{diabetes:'⚠️ If you are diabetic or on blood sugar medication, consult your doctor before use as this may affect glucose levels.'}},
  {name:'Body Slim X30 Tea Bags - Pomegranate',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Maxivita Exclusive Lutein Forte+ x45',category:'Eye Health',primary:'eye',goals:['eye'],who:['adult','woman','man'],warnings:{}},
  {name:'ESI Pure Melatonin 1.9mg X60 Gummies',category:'Melatonin',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'Vega Vitamin B12 1000Mcg  Tablets *30',category:'Vitamin B12',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Stim and Trim Fat Inferno X90 Capsules',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'Melatonin + Chamomile Act X30 Tea Bags',category:'Melatonin',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'Active B Complex + For Men X30 Capsules',category:'Vitamin B',primary:'energy',goals:['energy'],who:['adult','man'],warnings:{}},
  {name:'Pure Encapsulations Turmeric X30 Capsules',category:'Turmeric',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Vega Zinc Citrate 50Mg Vitamin X60 Tablets',category:'Zinc',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Health Aid Zinc Citrate 100Mg X100 Tablets',category:'Zinc',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'Lucovitaal Melatonin Forte 2mg X30 Lozenges',category:'Melatonin',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'Natroceutics Curcumin Complete X30 Capsules',category:'Turmeric',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Ultimate Nutrition Glucosamine 1000Mg x90 Capsules',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Mushrooms For Life Organic Lion\'s Mane Capsules X60',category:'Lion\'s Mane',primary:'focus',goals:['focus'],who:['adult','woman','man'],warnings:{}},
  {name:'Daile Dose Melt Away Extreme Fat Burner X90 Capsules',category:'Weight Management',primary:'weight',goals:['weight'],who:['adult','woman','man'],warnings:{}},
  {name:'German Calcium Effervescent Lemon Flavour X20 Tablets',category:'Calcium',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Ultimate Nutrition Glucosamine Chondroitin MSM X90 Tablets',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Zymerex Magnesium & Vitamin B6 Gummies x60 |  Orange Flavour',category:'Magnesium',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}},
  {name:'Melatonin + Forte 5 Complex and Valerian 45mg Act X60 Tablets',category:'Melatonin',primary:'sleep',goals:['sleep'],who:['adult','woman','man'],warnings:{}},
  {name:'Pure Encapsulations Glucosamine Chondroitin + MSM X30 Capsules',category:'Glucosamine',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Weightworld Lions Mane Mushroom with Black Pepper X365 Tablets',category:'Lion\'s Mane',primary:'focus',goals:['focus'],who:['adult','woman','man'],warnings:{}},
  {name:'German Zinc Effervescent Peach Passionfruit Flavour X20 Tablets',category:'Zinc',primary:'immune',goals:['immune'],who:['adult','woman','man'],warnings:{}},
  {name:'German Calcium + D3 Effervescent Orange Grapefruit Flavour X20 Tablets',category:'Calcium',primary:'joint',goals:['joint'],who:['adult','woman','man'],warnings:{}},
  {name:'Zymerex Magnesium, Potassium & Vitamin B Orange Gummies x60 | Mandarin Flavour',category:'Magnesium',primary:'energy',goals:['energy'],who:['adult','woman','man'],warnings:{}}
];